name: "Deployment"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_DEPLOY_KEY" > ~/.ssh/id_ed25519
          sudo chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          SSH_DEPLOY_KEY: ${{secrets.SSH_DEPLOY_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      - name: nixos-rebuild
        run: |
          nix-shell -p nixos-rebuild --run 'nixos-rebuild --use-remote-sudo --target-host root@bzh.social switch --flake .#bzh-social'
